[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pandacite"
version = "0.3.0"
description = "A Python-based citation manager"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
license-files = ["LICENSE"]

authors = [
  { name = "Dr. Pritam Kumar Panda", email = "pritam@stanford.edu" }
]

keywords = ["citation", "manager", "docx", "reference", "mendeley", "endnote"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Environment :: Console",
    "Topic :: Scientific/Engineering",
    "Operating System :: OS Independent"
]

dependencies = [
    "requests>=2.25",
    "python-docx>=0.8.11",
    "beautifulsoup4>=4.9",
    "colorama>=0.4",
    "prompt_toolkit>=3.0",
]


[project.optional-dependencies]
dev = [
    "pytest",
    "flake8",
    "black"
]

[project.scripts]
pandacite = "pandacite.cli:main"

[project.urls]
Homepage = "https://github.com/pritampanda15/pandacite"
Issues = "https://github.com/pritampanda15/pandacite/issues"

[tool.setuptools.packages.find]
include = ["pandacite*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
